#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';


use App\Command\TestApiCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new TestApiCommand());


$app->run();